name: test-plan-generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
      - openai
      - google-generativeai
      - gradio
      - pdfplumber
      - python-docx
      - fpdf
      - python-dotenv
